services:
  siephp-php83:
    container_name: siephp-php83
    build:
      context: .
      dockerfile: ./docker/dockerfile-siephp-php83
    tty: true
    stdin_open: true
    volumes:
      - .:/docker:rw,delegated

  siephp-php84:
    container_name: siephp-php84
    build:
      context: .
      dockerfile: ./docker/dockerfile-siephp-php84
    tty: true
    stdin_open: true
    volumes:
      - .:/docker:rw,delegated

  siephp-php85:
    container_name: siephp-php85
    build:
      context: .
      dockerfile: ./docker/dockerfile-siephp-php85
    tty: true
    stdin_open: true
    volumes:
      - .:/docker:rw,delegated
